# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee096221d222678b637d2c4acf7648a83400f711ef061058ebb0d6c945d62460e6e8c2929f7aecc8ab740d6df436cd922892818de64bbbaae1d6af6db6af1deb

test:
  secret_key_base: 7234e2a54bdf24eaef4542422c648e86955cbd035d989b709390efba8eb87eaef51c00448487d93342ecc982b11ad770b07d53f8e5503de35b6a3ef34533fe2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
